### ISSUE TITLE
Environment settings from the project setting are ignored

### ISSUE THREAD

**Issue by mfg92** [Magodra/GlowBorderEffect#4]
First of all, thank you very much for providing this addon to the community.

When I added the GlowBorderEffectRenderer to my scene, I noticed that the image quality dropped as there was no antialiasing and also the fog of my scene disappeared.
So I investigated how the addon works. My conclusion is that the whole scene is rendered twice (+ the glow prepass):
- inside the addon with the default WorldEnvironment settings for the ViewportScene
- outside the addon in the root viewport

So the addon
1. renders the whole scene
2. renders only the stuff that should get a glowing border (prepass)
3. blurs the prepass
4. combines the results of the previous three steps
5. places a 2D component with the resulting image over the whole screen, hiding the 3D scene that is rendered by default.

Performance-wise this is bad and many of the project settings are ignored by this approach.

I modified the addon so that it only creates the blurred borders, the rest of the container is transparent. This way the addon does not do the mixing of the scene and the glow itself, instead the normal overlay mechanism of godot does the job for us.

If you are interested in the code, I am happy to share it with you. Either as a ZIP so you can pick the parts you like or I can make a pull request.

**Comment by Magodra** [comment]
Sure if there are way to improve I would very much appreciate it. Pull
request might be good, then your contributions will be traced as well.

-Anders

man. 14. okt. 2024 kl. 18:40 skrev mfg92 ***@***.***>:

**Comment by Magodra** [comment]
Updated the effect to overlay the boarder. Added automatic mode that use current camera.
